<?php
class TheParent
{
    const SETUP = ['TEST' => 'HOI'];

    public function whatAmI()
    {
        return static::class;
    }
}

class TheChild extends TheParent
{
    public function testSomething(string $variable): string
    {
        return (mb_strlen($variable)) ? mb_substr($variable, 0, 1) : 'X';
    }
}

class TheGrandChild extends TheChild
{
    public function testSomething(string $variable): string
    {
        return mb_strtoupper($variable);
        // return parent::testSomething($variable); // TODO: Change the autogenerated stub
    }

    public function whatAmI()
    {
        return 'zoo';
        //return parent::whatAmI(); // TODO: Change the autogenerated stub
    }
}

abstract class TheAbstract
{
    public function __construct()
    {
    }
}


class World
{
    public function hello(): string
    {
        return "Hello " . __CLASS__;
    }
}

class Meek extends World
{
    public function __call(string $name, array $arguments)
    {
        return "I have the world";
    }
}

class A
{
    public static function foo() {
        echo static::who();
    }

    public static function who() {
        return 'A';
    }
}

class B extends A
{
    public static function test() {
        A::foo();
        parent::foo();
        self::foo();
    }
}

class C extends B
{
    public static function who() {
        echo 'C';
    }
}

// GENERATOR
function sowCrops() { return 'wheat'; }
function millWheat() { sleep(1); return 'flour'; }
function bake($flour) { return 'cupcake'; }

function generator() {
    $wheat = yield sowCrops();
    $flour = yield millWheat();
    return bake($flour);
}
$gen = generator();
foreach ($gen as $key => $value) {
    echo $key . ' => ' . $value . PHP_EOL;
}
var_dump(basename('index.php'));
// echo $gen->getReturn();
exit;
C::test();
exit;

echo (new TheParent())->whatAmI();
exit;
function testMyMeek(World $test): string
{
    return $test->hello();
}
$meek = new Meek();
echo testMyMeek($meek);
exit;
echo $meek->heslo();
exit;
$grandchild = new TheGrandChild();
echo $grandchild->testSomething('Olay');